config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/search' => 'search#index', :as => 'search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
require "json"

class SearchController < ApplicationController
  def index
    if params['lat'] && params['long']
      @response = Openweather::Search.by_location(params['lat'], params['long'])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWeather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Josefin+Slab:wght@300&display=swap' %>
     <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Josefin+Slab:wght@300&family=Monoton&display=swap' %>
     <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= form_with(url: search_path, method: "get", local: true, id: "hidden-form") do %>
    <%= hidden_field_tag(:lat) %>

    <%= hidden_field_tag(:long) %>

    <%= submit_tag("Submit?", id: "hidden-submit") %>
    <% end %>


    <div class="home-container">
        <div class="top">
            <h2>Find out the weather in your city</h2>
        </div>
        <div class="bottom">
            <div class="left">

                <p>Keep track of the weather with just one click!</p>
                <button id="weather-btn">Current Weather</button>
            </div>
            <div class="right">
                <%= image_tag("icons/clima.svg", class: 'home-svg') %>
            </div>
        </div>
    </div>


    <%= javascript_pack_tag 'homeButton' %>

app/views/search/index.html.erb
<% require "json" %>
<% require "time" %>

<% if @response %>
  <div class="weather-container">

    <div class="banner">
      <h2>Weather in <%= @response["name"] %></h2>
    </div>

    <div class="section weather-top">
      <% icon_id =  @response["weather"][0]["icon"] %>
      <%= image_tag("icons/#{icon_id}.png") %><br>
      <h2><b><%= @response["main"]["temp"].round() %>°</b></h2>
      <h2><%= @response["weather"][0]["main"] %></h2>
      <i><%#= @response["weather"][0]["description"] #%></i><br>
    </div>

    <div class="section temp">
      <p class="p2">Feels like <b><%= @response["main"]["feels_like"].round() %>°</b></p>
      <br>
      <div class="min-max">
        <div>
          <%= image_tag("icons/down-arrow.png", class: 'icon') %> <b><%= @response["main"]["temp_min"].round() %>°</b>
        </div>
        <div>
          <%= image_tag("icons/up-arrow.png", class: 'icon') %> <b><%= @response["main"]["temp_max"].round() %>°</b>
        </div>
      </div>
      <br>
      <p class="p3">Pressure at <%= @response["main"]["pressure"] %> hPa</p>
      <br>
      <p class="p3">Humidity at <%= @response["main"]["humidity"] %>%</p>
      <br>
    </div>

    <div class="section">
      <% time_zone = @response["timezone"] %>
      <% sunrise_time = Time.at(@response["sys"]["sunrise"]).utc.getlocal(time_zone) %>
      <% sunrise_time = sunrise_time.strftime("%I:%M %p")  %>
      <% sunset_time = Time.at(@response["sys"]["sunset"]).utc.getlocal(time_zone) %>
      <% sunset_time = sunset_time.strftime("%I:%M %p")  %>
      <div class="sunrise-sunset">
        <%= image_tag("icons/sunrise.png") %> <b><%= sunrise_time %></b>
        <%= image_tag("icons/sunset.png") %> <b><%= sunset_time %></b>
      </div>
    </div>

    <% if @response["clouds"] %>
      <div class="section">
        <%= @response["clouds"]["all"] %>% cloud coverage
      </div>
    <% end %>

    <% if @response["wind"] %>
      <div class="section">
        <%= @response["wind"]["speed"] %> MPH winds at <%= @response["wind"]["deg"] %> degrees<br>
      </div>
    <% end %>

    <% if @response["rain"] %>
      <div class="section">
        Rained <%= @response["rain"]["1h"] %>mm in the last hour.
        <% if @response["rain"]["3h"] %>
          <%= @response["rain"]["3h"] %>mm in the last 3 hours.
        <% end %>
      </div>
    <% end %>

    <% if @response["snow"] %>
      <div class="snow">
        Snowed <%= @response["snow"]["1h"] %>mm in the last hour.
        <% if @response["snow"]["3h"] %>
          <%= @response["snow"]["3h"] %>mm in the last 3 hours.
        <% end %>
      </div>
    <% end %>

  </div>
<% end %>